dpc-sdp/tide_site

composer.json
dev-init.sh
src/AliasManager.php
src/EventSubscriber/TideSiteGetRouteSubscriber.php
src/EventSubscriber/TideSiteRequestEventSubscriber.php
src/Plugin/Linkit/Substitution/Canonical.php
src/TideSiteServiceProvider.php
tests/behat/features/alias.feature
tests/behat/features/jsonapi.alias.feature
tests/behat/features/jsonapi.content.feature
tests/behat/features/jsonapi.feature
tests/behat/features/jsonapi.link_enhancer.feature
tests/behat/features/jsonapi.route.feature
tide_site.module
tide_site.services.yml

JIRA: https://digital-engagement.atlassian.net/browse/SDPA-1213
Related PRs:
* Tide Core: https://github.com/dpc-sdp/tide_core/pull/57
* Tide Media: https://github.com/dpc-sdp/tide_media/pull/19
* Tide API: https://github.com/dpc-sdp/tide_api/pull/28
* Tide Site: https://github.com/dpc-sdp/tide_site/pull/18
* Tide Webform: https://github.com/dpc-sdp/tide_webform/pull/21
* Tide News: https://github.com/dpc-sdp/tide_news/pull/14
* Tide Page: https://github.com/dpc-sdp/tide_page/pull/14
* Tide Event: https://github.com/dpc-sdp/tide_event/pull/24
* Tide Landing Page: https://github.com/dpc-sdp/tide_landing_page/pull/63
* Tide Monsido: https://github.com/dpc-sdp/tide_monsido/pull/13
* Tide Search: https://github.com/dpc-sdp/tide_search/pull/11
* Tide: https://github.com/dpc-sdp/tide/pull/39
* …

[SDPA-1213] Upgraded Tide Site to be compatible to JSON:API 2.x.

---

composer.json
src/Plugin/jsonapi/FieldEnhancer/EntityReferenceSiteEnhancer.php
tide_site.tokens.inc

Added Entity Reference Site enhancer.

---

config/install/views.view.summary_contents.yml
css/tide_site_layout.css
src/EventSubscriber/TideSiteRouteAlter.php
tide_site.install
tide_site.libraries.yml
tide_site.module
tide_site.services.yml

https://digital-engagement.atlassian.net/browse/SDPA-2274
Make changes to the Content summary page to include renaming of fields and additional filters. 
https://3t7x5h.axshare.com/#g=1&p=pages

Updated Content admin view.

---

composer.json
src/EventSubscriber/TideSiteGetCacheIdSubscriber.php
src/TideSiteServiceProvider.php

https://digital-engagement.atlassian.net/browse/SDPA-2992

[SDPA-2992] fix cache issue

---

src/EventSubscriber/TideSiteRouteAlter.php

https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-3112

[SDPA-3112] Detached view.summary_contents.page from /admin/content

---

config/install/views.view.summary_contents.yml
tide_site.install

https://digital-engagement.atlassian.net/browse/SDPA-3039

[SDPA-3039]Added bulk action button

---

config/install/core.entity_form_display.taxonomy_term.sites.default.yml
config/install/core.entity_view_display.taxonomy_term.sites.default.yml
config/install/field.field.taxonomy_term.sites.field_site_og_image.yml
config/install/field.storage.taxonomy_term.field_site_og_image.yml
config/optional/metatag.metatag_defaults.taxonomy_term__sites.yml
tide_site.info.yml
tide_site.install

JIRA: https://digital-engagement.atlassian.net/browse/SDPA-3088

Added og:image metatag for Sites.

---

config/install/views.view.summary_contents.yml
src/EventSubscriber/TideSiteRouteAlter.php
tide_site.module

https://digital-engagement.atlassian.net/browse/SDPA-3154
see https://github.com/dpc-sdp/content-vic-gov-au/pull/675 to learn more details.

[SDPA-3154] Improved summary_content performance

---

README.md
tide_site.drush.inc

[SDPSUP-813] : Added a drush command that updates site taxonomies based on values passed in via an Environment Variable.
[SDPSUP-813]: https://digital-engagement.atlassian.net/browse/SDPSUP-813

[SDPSUP-813] : Added a drush command that updates site taxonomies based on values passed in via an Environment Variable.

---

tide_site.install

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3237
1.  Updated version of tide_site to remove unwanted update hook.
dpc-sdp/tide#73
dpc-sdp/content-vic-gov-au#700

[SDPA-3237] Removed unrequired update_hook.

---

tide_site.module

* SDPA-3279 Fixed 404 issue.
* Updates adding addtional logic

SDPA-3279 Fixed 404 issue. (#41)

---

composer.json
dev-tools.sh
src/EventSubscriber/TideSiteGetCacheIdSubscriber.php
src/TideSiteServiceProvider.php

Removed invalid method calls for TideSiteGetCacheIdSubscriber.

---

composer.json
config/install/views.view.summary_contents_filters.yml
dev-tools.sh
tide_site.install

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3813
dpc-sdp/tide_core#128
dpc-sdp/tide_media#36
1. Fixed Content View
1. Deletes summary_contents
1. Disables content
1. Enables summary_contents_filters

[SDPA-3813] Update content view

---

dev-tools.sh
tide_site.install

https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-3786
1. add an update hook to tide_site.install for making site field to be required

[SDPA-3786] makes site field to be required. Release 1.3.1

---

tide_site.install

https://digital-engagement.atlassian.net/browse/SDPSUP-1832
1. Added hook dependencies.
https://github.com/dpc-sdp/tide_landing_page/pull/95
https://github.com/dpc-sdp/tide_core/pull/154

[SDPSUP-1832] Added hook dependencies.

---

config/install/views.view.summary_contents_filters.yml
config/install/views.view.tide_site_moderated_content_filters.yml
tide_site.install

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4419
**Added**
Added filters i.e. primary site and subsite for moderation content screen 
**Removed**
Removed language filter from moderation content screen 
Removed moderation state filter from overview content screen
**Related PR**
https://github.com/dpc-sdp/content-vic-gov-au/pull/897

[SDPA-4419] Updated content overview and moderation to include extra filters

---

src/TideSitePathAliasListBuilder.php
tide_site.module

https://digital-engagement.atlassian.net/browse/SDPA-4450
alters PathAliasListBuilder to disable the truncated alias.

[SDPA-4450] Turns off truncated alias in the alias list

---

config/install/views.view.summary_contents_filters.yml
tide_site.install

https://digital-engagement.atlassian.net/browse/SDPA-2970
1. apply `d/m/Y - H:i` to the view.
2. change the view yaml file accordingly

[SDPA-2970] change display of dates in CMS to Australian style DD/MM/YYYY

---

tide_site.module

Added support for Tide Share Link.

---

tide_site.module

* Added support for Tide Share Link.

Added support for Tide Share Link. (#74)

---

src/TideSiteMenuAutocreate.php
tests/src/Unit/TideSiteFieldsTest.php

1. removed deprecated functions
2. removed unnecessary mock

Updates existing unit tests

---

tide_site.module

Moved site fields to sidebar of node form.

---

composer.json
drush.services.yml
src/Commands/TideSiteCommands.php

1. Adds Drush 10 compatible version of Drush command.

[DDIDO-594] Updated Drush to 10.x

---

tide_site.module

https://digital-engagement.atlassian.net/browse/DDS-235

Fixed site fields missing from node/media form after site-install.

---

config/install/core.entity_form_display.taxonomy_term.sites.default.yml
config/install/core.entity_view_display.taxonomy_term.sites.default.yml
config/install/field.field.taxonomy_term.sites.field_site_social_links.yml
config/install/field.storage.taxonomy_term.field_site_social_links.yml
tide_site.install

1. Adds a setting for linking Social Media Channels that are associated with a Site.
**JIRA Ticket** https://digital-engagement.atlassian.net/browse/SDPA-4650

[SDPA-4650] Site social media links

---

config/install/views.view.summary_contents_filters.yml
tide_site.install

https://digital-engagement.atlassian.net/browse/SDPA-5849
1. Updated the view to show only distinct results.
2. Update hook to get in those changes to existing project.
It is also been tested in the scenario where a node has same title but different node ids. In that scenario it will show both the nodes because they are not distinct and they both have different node ids, but node title can be the same.

[SDPA-5849] Added changes to show only distinct results for summary content view.

---

composer.json
config/install/linkit.linkit_profile.site_content.yml
tide_site.install
tide_site.tokens.inc

**JIRA**
https://digital-engagement.atlassian.net/browse/SDPA-6277
**Test Environment**
https://nginx-php.pr-89.content-reference-sdp-vic-gov-au.sdp2.sdp.vic.gov.au/
**Changes**
1. Adds linkit.linkit_profile.site_content.yml file to config/install
2. Adds Drupal core patch to create a Token for publication status
3. Update script in tide_site.install file to import new configuration option to all sites
**Screenshots**

[SDPA-6026] Unable to easily search and find internal links

---

.circleci/config.yml
dev-tools.sh
modules/tide_site_simple_sitemap/src/Plugin/simple_sitemap/SitemapGenerator/TideDefaultSitemapGenerator.php

https://digital-vic.atlassian.net/browse/SRM-587
Updating bay_imager_version to 5.x to get the php-8.1

Updated the bay image version.

---

composer.json
patches/video_embed_field/video_embed_field_6.patch

Using a noncanonical repository (fork) that originates from a Drupal ticket for issue resolution can potentially lead to a broken composer. This may happen if the changes are merged into the main branch and the forked repository is subsequently closed and deleted.

Remove noncanonical repos

---

composer.json
modules/tide_site_theming/config/install/field.field.taxonomy_term.sites.field_bottom_corner_graphic.yml
modules/tide_site_theming/config/install/field.field.taxonomy_term.sites.field_site_favicon.yml
modules/tide_site_theming/config/install/field.field.taxonomy_term.sites.field_top_corner_graphic.yml
modules/tide_site_theming/config/install/field.storage.taxonomy_term.field_bottom_corner_graphic.yml
modules/tide_site_theming/config/install/field.storage.taxonomy_term.field_site_favicon.yml
modules/tide_site_theming/config/install/field.storage.taxonomy_term.field_top_corner_graphic.yml
modules/tide_site_theming/tide_site_theming.install
modules/tide_site_theming/tide_site_theming.module

**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7914
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7916
For Ripple 2 to manage favicon and header corner graphics from CMS.
1.  Added favicon.
2. Added header corner graphics.

[SDPAP-7914] BE favicon icon for ripple 2.

---

composer.json
config/install/core.entity_form_display.taxonomy_term.sites.default.yml
config/install/core.entity_view_display.taxonomy_term.sites.default.yml
config/install/field.field.taxonomy_term.sites.field_print_friendly_logo.yml
config/install/field.storage.taxonomy_term.field_print_friendly_logo.yml
tide_site.install

**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7526
1.  Add new field Print-friendly logo.

[SDPA-7526] BE new field print-friendly logo for R2.
