dpc-sdp/tide_site

- config/install/core.entity_form_display.taxonomy_term.sites.default.yml
- tide_site.info.yml
- tide_site.module
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-960
PR in content-vic-gov-au: https://github.com/dpc-sdp/content-vic-gov-au/pull/285
This PR fixed the following error messages during the `composer:app db-import` step:
```php
error: Call to a member function getValues() on null in /app/docroot/modules/contrib/tide_site/tide_site.module on line 637 #0 /app/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(539): tide_site_search_api_index_items_alter(Object(Drupal\search_api\Entity\Index), Array, NULL)
#1 /app/docroot/modules/contrib/search_api/src/Entity/Index.php(963): Drupal\Core\Extension\ModuleHandler->alter('search_api_inde...', Object(Drupal\search_api\Entity\Index), Array)
#2 /app/docroot/modules/contrib/search_api/src/Utility/PostRequestIndexing.php(71): …
```
> [SDPA-960] Added check for null values.

- tide_site.install
SDPA-3154 Added an update hook for updating views.view.summary_contents
In the [last PR](https://github.com/dpc-sdp/tide_site/pull/32), we should add an update hook, but we didn't.
This PR is for fixing the issue described above.
> [SDPA-3154] Added an update hook

- tide_site.module
1. Create a Landing page for Vic Gov. Site and Primary Site and save/publish
2. Change for the landing page the  Site and Primary Site to aboriginal victoria and publish - seems to work okay
3. Change for the landing page the  Site and Primary Site to Multicultural and publish  - this will 404 on save
4. Change for the landing page the  Site and Primary Site to aboriginal victoria  and set Site value to Vic Gov also and publish  - this will save okay but accessing the content on the left in the content page will 404
field value changing didn't kick-off alias regenerating. 
fixed by adding new logic inside `hook_ENTITY_TYPE_update`  and removed `hook_ENTITY_TYPE_presave`
JIRA issue: https://digital-engagement.atlassian.net/browse/SDPA-3279
relates to …
> SDPA-3279 Fixed 404 issue.

- dev-tools.sh
- tide_site.install
https://digital-engagement.atlassian.net/browse/SDPA-3786
1. adds an update hook `tide_media_update_8010`
2. updates tide_media compatible with tide_core 1.5.4
3. change `GH_COMMIT` to `GH_COMMIT=COMMIT_SHA` in the dev-tools.sh file
https://github.com/dpc-sdp/content-vic-gov-au/pull/796
https://github.com/dpc-sdp/tide_media/pull/34
> SDPA-3786 makes site field to be required.

- tide_site.install
SDPA-4029 update permissions for approver and site_admin
* 1. approver and site_admin cannot delete sites terms.
* 2. revoke `administer taxonomy` permission.
* 3. assign `access taxonomy overview` permission.
https://digital-engagement.atlassian.net/browse/SDPA-4029
add an update hook
https://github.com/dpc-sdp/content-vic-gov-au/pull/847
> SDPA-4029 update permissions

- dev-tools.sh
- tide_site.install
Fix fatal errors when running update.
```
Error: Call to a member function setStatus() on null in tide_site_update_8009() (line 224 of /app/docroot/modules/contrib/tide_site/tide_site.install)
```
> Fixed fatal errors in update hooks.

- config/install/field.field.taxonomy_term.sites.field_site_logo.yml
- tests/behat/features/fields.media.feature
- tide_site.install
This PR is to enable the `alt` field for Site logo as per request from WorkSafe.
> Enabled alt field for site logo.

- src/AliasStorageHelper.php
Issue:
- Create a landing page "Standup Session" and save it as published
- Create event "Standup Session" and save it as draft. A new alias will be generated.
- Change moderation state from draft to published and click save. Alias will be removed and changed to node/123
The flow of condition is:
- This hook "tide_site_node_update" is trigerred on node_update
- Do a check if the alias doesnt exists. If it doesn't then create a new unique alias i.e. site-391/event-blah
- Do a check if the alias exists. Our code would not create a new alias i.e. site-391/event-blah but instead below will happen:
- Drupal pathauto will get trigerred and it will create a new alias i.e. /event-blah
- This hook "tide_site_path_alias_update" will get called and it will remove the new alias built by drupal i.e. …
> Removed checking if the alias does exists on node update.

- config/install/field.field.taxonomy_term.sites.field_site_logo.yml
- tide_site.install
This feature will enable svg as allowed filetype for sites_logo taxonomy. It looks like some of the fields already allow svg filetype and this field doesnt.
JIRA Ticket: https://digital-engagement.atlassian.net/browse/TVD-65
> Enable svg site logo

- modules/tide_site_preview/src/Plugin/Block/PreviewLinksBlock.php
https://digital-engagement.atlassian.net/browse/SW-705
1. Some routes that have a 'node' parameter don't necessarily hydrate the parameter, e.g. /node/$nid/revisions/$vid/revert. This change checks that $node is properly populated and sets it to NULL if not.
> Check that $node is properly populated before continuing

- tide_site.module
Added condition to check if config sync is running before we create fields on new content type.
When a new content type is created its done through updatedb process which will trigger entity_bundle_create. Once it is done we can do a config export which will give us two new fields.
If we run the deploy process config import will again try to create the content type and run entity_bundle_create hook which will error out because now the field exists. This will also stop any layout changes for the content type form display as it will try to add two new fields to the form layout display and overwrite any layout changes done by us.
> Added condition to check if config sync is running before field creation

- tide_site.module
https://digital-engagement.atlassian.net/browse/SW-827
For the card consolidation story, a new enhancer is added named cardLinkEnhancer. When an internal link is added to the card link field and the added links belong to another site, the FE throws an error on trying to access that link. There is a alter hook for tide_path_enhancer `tide_site_tide_path_enhancer_undo_transform_alter` that resolves this and the same functionality is need for the cardLinkEnhancer alter hook.
1. Added functionality in the cardLinkEnhancer alter hook to handle the link that belongs to other sites.
https://github.com/dpc-sdp/tide_landing_page/pull/131
A ticket is created to build a helper function which will be called in both of the alter hook for path enhancer and cardLinkEnhancer as they both are doing the …
> [SW-827] Added alter hook for cardLinkEnhancer to handle the url belongs to other sites.

- modules/tide_site_preview/src/Plugin/Block/PreviewLinksBlock.php
- modules/tide_site_preview/src/TideSitePreviewHelper.php
- modules/tide_site_preview/tide_site_preview.services.yml
Changed:
1) Refactor the preview link block plugin to expose buildFrontendPreviewLink() and getNodeFrontendUrl() as a service.
> [SDPA-5674] Refactor Tide Site Preview Link Builder

- tide_site.install
1. `drush updb` gets failed by running this hook.
2. it happens in some projects, as some configurations are exported already.
check if the config exists or not.
> Fixes an issue caused by existing config

- modules/tide_site_simple_sitemap/src/Plugin/simple_sitemap/SitemapGenerator/TideDefaultSitemapGenerator.php
https://digital-engagement.atlassian.net/browse/SW-2075
sitemaps.xml is sometimes broken, and all site-based indexes will be gone.
It might be because of a memory issue. sometimes core cronjob break when sitemap.xml indexing runs out of memory, and all sitemaps will be gone.
so, we have prepared 2 ways to prevent the disappearing sitemaps.
1. split sitemaps cronjob from drupalcore cronjobs to its own.
- https://github.com/dpc-sdp/ansible-role-sdp-tide-platform/pull/28/files
2. clean up the memory cache when the site-based sitemap.xml loop is done.
- https://github.com/dpc-sdp/tide_site/pull/104/files#diff-3d252e549b49a579815e4aa03acdf1dd4b508a2ef569a05435f397e389d6145dR92
we have tested it for a week, looks fine.
https://nginx-php.pr-1385.content-vic.sdp2.sdp.vic.gov.au/
> [SW-2075] Clean up memory when a site-based index is done.

- composer.json
- dev-tools.sh
- modules/tide_site_theming/config/install/field.field.taxonomy_term.sites.field_site_feature_flags.yml
- modules/tide_site_theming/config/install/field.storage.taxonomy_term.field_site_feature_flags.yml
- modules/tide_site_theming/tide_site_theming.install
- modules/tide_site_theming/tide_site_theming.module
- modules/tide_site_theming/tide_site_theming.permissions.yml
https://digital-vic.atlassian.net/browse/R20-335
BE PR: https://nginx-php.pr-171.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
1. Additional field identical to the tide_site_theming; field_site_theme_values
2. Adds new key value paired fields in the site taxonomy
> [R20-335] Be able to define site wide "feature flags" from Tide Site config

- composer.json
- modules/tide_site_theming/tide_site_theming.module
https://digital-vic.atlassian.net/browse/SDPAP-7432
> [SDPAP-7432] Fixes errors on node creation page

- composer.json
linkit released beta 4 for 6.x version which breaks the patch
Updated the patch to be compatible with the new release
Move the patch to tide_core
> Updated patch.

- modules/tide_site_preview/src/Plugin/Block/PreviewLinksBlock.php
https://digital-vic.atlassian.net/browse/SRM-702
Some of the $vid values returned as object and which causes illegal offset type error when calling the `loadRevision` function.
Scenario - Go to a node in any CMS and click on the revision tab. Then click on any previous revision and then the CMS will throw error.
9.4 returns the vid directly from here - `$revision = $this->routeMatch->getParameter('node_revision');`
https://github.com/dpc-sdp/tide_site/issues/121
> [SRM-702] Fix for revision loading throws error on illegal offset type.

- modules/tide_site_preview/src/Plugin/Block/PreviewLinksBlock.php
- modules/tide_site_preview/src/TideSitePreviewHelper.php
- modules/tide_site_preview/tide_site_preview.install
- modules/tide_site_simple_sitemap/tide_site_simple_sitemap.install
- modules/tide_site_simple_sitemap/tide_site_simple_sitemap.module
- tide_site.install
- tide_site.module
> Sort use alphabetically.

- modules/tide_site_theming/src/TideSiteThemingOperation.php
- modules/tide_site_theming/tide_site_theming.install
- tide_site.install
https://digital-vic.atlassian.net/browse/SDPAP-7999
The print logo update hook was not checking the existing sync directory settings, instead it was taking all the configs from the config install and updating the form and view display. This ended up removing the changes made by the submodule into the view and form display.
1. Updated the hook to use better way to set a new component in an existing view and form display. (This will avoid removing any custom or any changes made by other module in the same view or form display )
2. Update tide_site_theming module to add the new update hook changes into the install hook and also separating the install operation in a class function.
> [SDPAP-7999] Fixing update hook to not to change existing settings during update.

- tide_site.install
This error show up during cofig-export in ci build.
```
[error]  'field_storage_config' entity with ID 'taxonomy_term.field_print_friendly_logo' already exists. 
>  [error]  Update failed: tide_site_update_8026
```
Updated the id check process.
> [SDPAP-7999] Updated the hook to check the existing cofig id properly.

- modules/tide_site_theming/src/TideSiteThemingOperation.php
`[error]  Error: Class "Drupal\tide_site_theming\Drupal" not found in Drupal\tide_site_theming\TideSiteThemingOperation::requiredChangesForTheming() (line 179 of /app/docroot/modules/contrib/tide_site/modules/tide_site_theming/src/TideSiteThemingOperation.php) #0 /app/docroot/modules/contrib/tide_site/modules/tide_site_theming/tide_site_theming.install(20): Drupal\tide_site_theming\TideSiteThemingOperation::requiredChangesForTheming()`
Added the missing `\` before Drupal to fix the error.
> Updated the class to fix the missing drupal class.

- src/Commands/TideSiteCommands.php
https://digital-vic.atlassian.net/browse/SDPAP-7814
The drush command function missing the Term class reference.
Added the missing term use statement and the command is compatible with drush command, still works perfectly.
Added the changes in the tide-platform lagoon yml template to roll out the missing drush command for all SDP projects.
https://github.com/dpc-sdp/ansible-role-sdp-tide-platform/pull/82
> [SDPAP-7814] Added missig term reference.

- src/Commands/TideSiteCommands.php
The content reference site does not have the site id created. It only gets created when the demo content gets enabled. The demo site id is 8888 and that is what has been used for the reference site FE. This is causing issue when running the drush command to update the domains. The drush command when it was written, there wasn't any scenario like this but now it is once exceptional scenario only for reference site.
Added a term check on the drush command, so that it does not break the build for the reference site.
> Added null check.

- modules/tide_site_simple_sitemap/tide_site_simple_sitemap.module
https://digital-vic.atlassian.net/browse/SDPAP-8510
when creating a new sitemap, e.g. site-9203, via UI, the default url `/` doesn't create automatically. 
fixed by implementing a `hook_ENTITY_TYPE_insert`
> [SDPAP-8510] Sitemap doesn't create the custom URL automatically in UI

- src/EventSubscriber/TideSiteResourceObjectNormalizationCacher.php
Update TideSiteResourceObjectNormalizationCacher.php  for Drupal 10 as it was giving conflicts in some BEs like content-vic. 
This pr was tested in content-vic: https://nginx-php.pr-1665.content-vic.sdp4.sdp.vic.gov.au/
> Update function for Drupal 10
